[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[window]
startup_mode = "Maximized"

[font.normal]
  family = "Hack Nerd Font Mono"
  style = "Regular"

[font.italic]
  family = "Hack Nerd Font Mono"
  style = "Italic"

[font.bold]
  family = "Hack Nerd Font Mono"
  style = "Bold"

[[hints.enabled]]
regex = '(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+'
command = "/usr/bin/open"
post_processing = true
  [hints.enabled.mouse]
    enabled = true
    mods = "Control"
