[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]

[window]
startup_mode = "Maximized"

[font.normal]
  family = "Hack Nerd Font Mono"
  style = "Regular"

[font.italic]
  family = "Hack Nerd Font Mono"
  style = "Italic"

[font.bold]
  family = "Hack Nerd Font Mono"
  style = "Bold"
